---
title: "Test"
author: "Jess"
date: "9/17/2020"
output: html_document
---

```{r}
library(taxize)
library(httr)
library(XML)
library(rscopus)
library(specieshindex)
library(reactable)
library(formattable)

taxonomy <- read.csv(file = "taxonomy.csv", header = T)
```

```{r}
DownloadAll <- function(data) {
  totalspp <- nrow(data)
  APIkey <- "442b9048417ef20cf680a0ae26ee4d86"
  datalist = list()
  print("Starting loop now.")
  for (i in 1:totalspp) {
    print(i)
    species <- FetchSpTAK(data$genusName[i],
                          data$speciesName[i], 
                          APIkey)
    sppindex <- Allindices(species, genus = data$genusName[i], species = data$speciesName[i])
    print(paste(length(species), "records retrieved."))
    datalist[[i]] <- sppindex
  }
  return(datalist)
}
```

```{r}
marsupials <- DownloadAll(taxonomy)
marsupial_df<-bind_rows(marsupials)
```

```{r}
unit.scale = function(x) (x - min(x)) / (max(x) - min(x))
```

```{r}
marsupials_df <- marsupial_df[,1:13] %>%
  gsub("_", " ", marsupial_df$genus_species, fixed = T) %>%
  rename("Binomial name" = genus_species,
         "Species name" = species,
         "Genus name" = genus,
         Publications = publications,
         Citations = citations,
         Journals = journals,
         Articles = articles,
         Reviews = reviews,
         "Years publishing" = years_publishing,
         "h-index" = h,
         "m-index" = m,
         "i10 index" = i10,
         "h5 index" = h5)


formattable(marsupials_df, list(
  "h-index" = color_bar("#FF9E9E", fun = unit.scale),
  "m-index" = color_bar("#FFE49E", fun = unit.scale),
  "i10 index" = color_bar("#9EFFAF", fun = unit.scale),
  "h5 index" = color_bar("#9EDBFF", fun = unit.scale)
))
```


